//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.14 at 02:10:10 AM IST 
//


package commercial_bank_portal.generatedSource;

import jakarta.xml.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Header"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CompanyRegName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="CompanyRegNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="EmployeeInfo" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="EpfNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="NIC" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="BankInfo"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="BankName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="BankAccount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="BankCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="BranchCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="Salary" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Footer"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CtrlSum" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "employeeInfo",
    "footer"
})
@XmlRootElement(name = "DocumentRequest")
public class DocumentRequest {

    @XmlElement(name = "Header", required = true)
    protected Header header;

    @XmlElement(name = "EmployeeInfo")
    protected List<EmployeeInfo> employeeInfo;

    @XmlElement(name = "Footer", required = true)
    protected Footer footer;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the employeeInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the employeeInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmployeeInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmployeeInfo }
     * 
     * 
     */
    public List<EmployeeInfo> getEmployeeInfo() {
        if (employeeInfo == null) {
            employeeInfo = new ArrayList<EmployeeInfo>();
        }
        return this.employeeInfo;
    }

    /**
     * Gets the value of the footer property.
     * 
     * @return
     *     possible object is
     *     {@link Footer }
     *     
     */
    public Footer getFooter() {
        return footer;
    }

    /**
     * Sets the value of the footer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Footer }
     *     
     */
    public void setFooter(Footer value) {
        this.footer = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="EpfNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="NIC" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="BankInfo"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="BankName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="BankAccount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="BankCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="BranchCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="Salary" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "epfNo",
        "firstName",
        "middleName",
        "lastName",
        "nic",
        "bankInfo"
    })
    public static class EmployeeInfo {

        @XmlElement(name = "EpfNo", required = true)
        protected String epfNo;
        @XmlElement(name = "FirstName", required = true)
        protected String firstName;
        @XmlElement(name = "MiddleName", required = true)
        protected String middleName;
        @XmlElement(name = "LastName", required = true)
        protected String lastName;
        @XmlElement(name = "NIC", required = true)
        protected String nic;
        @XmlElement(name = "BankInfo", required = true)
        protected BankInfo bankInfo;

        /**
         * Gets the value of the epfNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEpfNo() {
            return epfNo;
        }

        /**
         * Sets the value of the epfNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEpfNo(String value) {
            this.epfNo = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the middleName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMiddleName() {
            return middleName;
        }

        /**
         * Sets the value of the middleName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMiddleName(String value) {
            this.middleName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastName(String value) {
            this.lastName = value;
        }

        /**
         * Gets the value of the nic property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNIC() {
            return nic;
        }

        /**
         * Sets the value of the nic property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNIC(String value) {
            this.nic = value;
        }

        /**
         * Gets the value of the bankInfo property.
         * 
         * @return
         *     possible object is
         *     {@link BankInfo }
         *     
         */
        public BankInfo getBankInfo() {
            return bankInfo;
        }

        /**
         * Sets the value of the bankInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link BankInfo }
         *     
         */
        public void setBankInfo(BankInfo value) {
            this.bankInfo = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="BankName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="BankAccount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="BankCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="BranchCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="Salary" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "bankName",
            "bankAccount",
            "bankCode",
            "branchCode",
            "salary"
        })
        public static class BankInfo {

            @XmlElement(name = "BankName", required = true)
            protected String bankName;
            @XmlElement(name = "BankAccount", required = true)
            protected String bankAccount;
            @XmlElement(name = "BankCode", required = true)
            protected String bankCode;
            @XmlElement(name = "BranchCode", required = true)
            protected String branchCode;
            @XmlElement(name = "Salary")
            protected double salary;

            /**
             * Gets the value of the bankName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBankName() {
                return bankName;
            }

            /**
             * Sets the value of the bankName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBankName(String value) {
                this.bankName = value;
            }

            /**
             * Gets the value of the bankAccount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBankAccount() {
                return bankAccount;
            }

            /**
             * Sets the value of the bankAccount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBankAccount(String value) {
                this.bankAccount = value;
            }

            /**
             * Gets the value of the bankCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBankCode() {
                return bankCode;
            }

            /**
             * Sets the value of the bankCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBankCode(String value) {
                this.bankCode = value;
            }

            /**
             * Gets the value of the branchCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBranchCode() {
                return branchCode;
            }

            /**
             * Sets the value of the branchCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBranchCode(String value) {
                this.branchCode = value;
            }

            /**
             * Gets the value of the salary property.
             * 
             */
            public double getSalary() {
                return salary;
            }

            /**
             * Sets the value of the salary property.
             * 
             */
            public void setSalary(double value) {
                this.salary = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="CtrlSum" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ctrlSum"
    })
    public static class Footer {

        @XmlElement(name = "CtrlSum")
        protected double ctrlSum;

        /**
         * Gets the value of the ctrlSum property.
         * 
         */
        public double getCtrlSum() {
            return ctrlSum;
        }

        /**
         * Sets the value of the ctrlSum property.
         * 
         */
        public void setCtrlSum(double value) {
            this.ctrlSum = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="CompanyRegName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="CompanyRegNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "companyRegName",
        "companyRegNo"
    })
    public static class Header {

        @XmlElement(name = "CompanyRegName", required = true)
        protected String companyRegName;
        @XmlElement(name = "CompanyRegNo", required = true)
        protected String companyRegNo;

        /**
         * Gets the value of the companyRegName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompanyRegName() {
            return companyRegName;
        }

        /**
         * Sets the value of the companyRegName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompanyRegName(String value) {
            this.companyRegName = value;
        }

        /**
         * Gets the value of the companyRegNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompanyRegNo() {
            return companyRegNo;
        }

        /**
         * Sets the value of the companyRegNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompanyRegNo(String value) {
            this.companyRegNo = value;
        }

    }

}
