//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.14 at 02:10:10 AM IST 
//


package commercial_bank_portal.generatedSource.hris;

import jakarta.xml.bind.annotation.*;
import lombok.Getter;
import lombok.Setter;

import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "header",
        "employeeInfo",
        "footer"
})
@XmlRootElement(name = "DocumentRequest")
@Getter
@Setter
public class DocumentRequest {

    @XmlElement(name = "Header", required = true)
    protected Header header;

    @XmlElement(name = "EmployeeInfo")
    protected List<EmployeeInfo> employeeInfo;

    @XmlElement(name = "Footer", required = true)
    protected Footer footer;
}
