//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.14 at 02:10:10 AM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.commercialbankportal.com/bankTransfer", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package commercial_bank_portal.generatedSource.hris;
